site_name: DANS Dataverse - Software Heritage Deposit Form
# site_url: https://example.com/

repo_name: DANS Dataverse - Software Heritage Deposit Form
repo_url: https://github.com/Dans-labs/swh-docs

dev_addr: "127.0.0.1:8080"

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json

#theme:
#  name: mkdocs
#  nav_style: dark


markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: False
      use_pygments: False
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true

# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
nav:
  - Home: 'index.md'
  - 'Deposit Form for Researchers':
    - 'Introduction': 'researchers.md'
    - 'Prerequisites': 'prerequisites.md'
    - 'Instructions': 'user_manual.md'
  - Developers documentation:
    - 'Introduction': 'developers.md'

plugins:
  - search
  - markdownextradata: { }
  - mermaid2

extra:
  hyperlink:
    ext:
      swh: https://www.softwareheritage.org/
      deposit: https://swh.dansdemo.nl/
      fc4e: https://faircore4eosc.eu/
      dataverse: https://dataverse.eosc.dansdemo.nl/

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/
